repos:
  - repo: local
    hooks:
      - id: check-vscode-changes
        name: Check for .vscode changes
        entry: bash -c 'git diff --cached --name-only | grep "^\.vscode/" && echo "Error .vscode changes detected. Please remove them before committing." && exit 1 || exit 0'
        language: system
        stages: [commit]
